"""init_models

Revision ID: e11c3a62ae73
Revises: db69bd5763ca
Create Date: 2026-02-26 15:23:03.493381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11c3a62ae73'
down_revision: Union[str, Sequence[str], None] = 'db69bd5763ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'busy', name='operator_status'), server_default='offline', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operator_status', 'operators', ['status'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'waiting', 'resolved', 'closed', name='ticket_status'), server_default='new', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='2', nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('waiting_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority BETWEEN 1 AND 4', name='ck_ticket_priority_range'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_operator_status', 'tickets', ['operator_id', 'status'], unique=False)
    op.create_index('ix_ticket_status', 'tickets', ['status'], unique=False)
    op.create_index('ix_ticket_waiting_since', 'tickets', ['waiting_since'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(client_id IS NOT NULL AND operator_id IS NULL) OR (client_id IS NULL AND operator_id IS NOT NULL)', name='ck_message_author_xor'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_ticket_created', 'messages', ['ticket_id', 'created_at'], unique=False)
    op.add_column('clients', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'clients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'email')
    op.drop_index('ix_message_ticket_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_ticket_waiting_since', table_name='tickets')
    op.drop_index('ix_ticket_status', table_name='tickets')
    op.drop_index('ix_ticket_operator_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_operator_status', table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
